# secrets.example.toml

[gcp_service_account]
# 여기에 서비스 계정 JSON 키 전체를 붙여넣으세요
# 예시 필드:

type = "service_account"
project_id = "my-gcp-project"
private_key_id = "abcd1234efgh5678"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEv...snip...\n-----END PRIVATE KEY-----\n"
client_email = "my-service-account@my-gcp-project.iam.gserviceaccount.com"
client_id = "12345678901234567890"
token_uri = "https://oauth2.googleapis.com/token"


gsheet_id = "1DnV3Zcqm-G05H42R9nGo0p8YCE-Ycur6UigeO3p_gpc"
# worksheet = "reservations"  # (선택)
